# Generated by Django 4.2.2 on 2023-07-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.CharField(max_length=30)),
                ('clickTime', models.BigIntegerField()),
                ('patchNumber', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('isRipe', models.BooleanField()),
            ],
            options={
                'db_table': 'task_clicks',
            },
        ),
    ]
