# Generated by Django 4.2.2 on 2023-07-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=30)),
                ('start_time', models.BigIntegerField(default='NA')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Task_clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=30)),
                ('click_time', models.BigIntegerField()),
                ('patch_number', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('is_ripe', models.BooleanField()),
            ],
            options={
                'db_table': 'task_clicks',
            },
        ),
    ]
