# Generated by Django 4.2.2 on 2023-07-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_task_app', '0002_alter_task_clicks_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task_clicks',
            table='labtoolz.task_clicks',
        ),
    ]
