# Generated by Django 4.2.2 on 2023-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_task_app', '0002_subjects_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oci_questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=50)),
                ('question_1', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_2', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_3', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_4', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_5', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_6', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_7', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_8', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_9', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_10', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_11', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_12', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_13', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_14', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_15', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_16', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_17', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
                ('question_18', models.IntegerField(choices=[(0, 'Not at all'), (1, 'A little'), (2, 'Moderately'), (3, 'A lot'), (4, 'Extremely')])),
            ],
            options={
                'db_table': 'oci_questionnaire',
            },
        ),
    ]
