# Generated by Django 4.2.2 on 2023-07-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_task_app', '0003_alter_task_clicks_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task_clicks',
            table='task_clicks',
        ),
    ]
