# Generated by Django 4.2.2 on 2023-07-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_task_app', '0004_subjects_prolific_pid_subjects_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='prolific_pid',
        ),
    ]
