# Generated by Django 4.2.2 on 2023-07-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_task_app', '0004_alter_task_clicks_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
    ]
