# Generated by Django 4.2.2 on 2023-08-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_task_app', '0005_remove_subjects_prolific_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aaq_questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=50)),
                ('question_1', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('question_2', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('question_3', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('question_4', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('question_5', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('question_6', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
                ('question_7', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')])),
            ],
            options={
                'db_table': 'aaq_questionnaire',
            },
        ),
        migrations.CreateModel(
            name='Dass_questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=50)),
                ('question_1', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_2', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_3', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_4', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_5', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_6', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_7', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_8', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_9', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_10', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_11', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_12', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_13', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_14', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_15', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_16', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_17', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_18', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_19', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_20', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
                ('question_21', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')])),
            ],
            options={
                'db_table': 'dass_questionnaire',
            },
        ),
    ]
