# Generated by Django 4.2.2 on 2023-07-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_task_app', '0005_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_clicks',
            old_name='clickTime',
            new_name='click_time',
        ),
        migrations.RenameField(
            model_name='task_clicks',
            old_name='isRipe',
            new_name='is_ripe',
        ),
        migrations.RenameField(
            model_name='task_clicks',
            old_name='patchNumber',
            new_name='patch_number',
        ),
        migrations.RenameField(
            model_name='task_clicks',
            old_name='subjectID',
            new_name='subject_id',
        ),
    ]
