# Generated by Django 4.2.2 on 2023-07-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_task_app', '0006_rename_clicktime_task_clicks_click_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subjectID',
            new_name='subject_id',
        ),
    ]
