# Generated by Django 4.2.2 on 2023-08-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_task_app', '0006_aaq_questionnaire_dass_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_clicks',
            name='color',
            field=models.CharField(default='NA', max_length=30),
        ),
        migrations.AddField(
            model_name='task_clicks',
            name='is_green',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='task_clicks',
            name='is_ripe',
            field=models.BooleanField(default='False'),
        ),
    ]
