# Generated by Django 4.2.2 on 2023-07-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foraging_task_app', '0007_rename_subjectid_subjects_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='start_time',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
